---

# Debian install tasks

- name: 'INSTALL | Install account management packages'
  become: True
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    update_cache: True
    cache_valid_time: 3600
  with_items: "{{ account_management_packages }}"
